### ISSUE TITLE
Standardize uppercase use in drop down menu

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#105]
Small text edit - the terms in the drop-down should be consistent. Do we want to go with, for example, Prepared Family Meals or Prepared family meals? Right now we mix the two strategies:

![Screen Shot 2020-04-08 at 10 42 47 PM](https://user-images.githubusercontent.com/58799043/78852512-84783500-79ea-11ea-8bae-6c5f03e3645f.png)

**Comment by readingdancer** [comment]
I have changed them all to upper case on the first word only. This will be updated on my next release.
