### ISSUE TITLE
Mobile friendly value boxes

### ISSUE THREAD

**Issue by jasonajones73** [code-for-chapel-hill/COVID-Support-For-CH#13]
**Need work on an existing feature? **
(a) I'm noticing that when the dashboard is made smaller, everything resizes appropriately except for the value boxes. Not sure if there is a way to handle this in CSS?

(b) Maybe add some inline CSS styling that takes care of that?

**Comment by readingdancer** [comment]
Hi @jasonajones73 , if you take another look you should see the site has moved on since you last looked at it. This ticket is not resolved yet as I still have a little bit more styling to do, but it's getting there :)

**Comment by readingdancer** [comment]
@jasonajones73 or @KM-Hanson could you check on mobile that you are happy with the top boxes so we can close this ticket?

**Comment by jasonajones73** [comment]
Looks good!
