### ISSUE TITLE
Add multi-lingual support for the user interface.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/COVID-Support-For-CH#15]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

Allow the interface to be easily translatable into multiple languages.

(b) What do we need to code next?

Add a multilingual framework and change all text labels to use the framework, this should allow others to help add additional languages.

**Describe alternatives you've considered**
I don't know if there is a special R package for multi-lingual interfaces, if not, this might be a good solution...
https://github.com/i18next/react-i18next
https://github.com/Appsilon/shiny.i18n

**Comment by KM-Hanson** [comment]
Our goals for adding multi-lingual support:
(1) Keep the code separate from the translations to make the code cleaner to read and easier to understand.

(2) Make it easier for a non-technical team member to provide translations. Each translation will be in a separate language file.

(3) Translation would mainly pertain to (a) user-choice options and (b) notes about the resources (e.g., "Look for the yellow school bus!"

**Comment by readingdancer** [comment]
The pull request https://github.com/code-for-chapel-hill/COVID-Support-For-CH/pull/22 should fix this issue :)
