### ISSUE TITLE
Update "What do you need?" drop-down menu

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#25]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

This drop-down menu helps users filter the dataset to find the resources that they need.
Currently, the drop-down shows 5 items. We need to add items and edit the order or the items displayed.

(b) What do we need to code next?
The drop down under "What do you need?" should read as follows:

Groceries
Restaurants
Free Meals
Pharmacy
Pet Supplies
Entertainment

**Describe alternatives you've considered**
N/A

**Additional context**
If we update this in the English version, do the changes automatically trigger changes in the translated versions?

**Comment by readingdancer** [comment]
Hi @KM-Hanson the translations so far have nearly all been done by me adding them, they have to be added to the translation files manually. If you use the BabelEdit tool it makes it very easy as it integrates with Google Translate, however the tool is only free for 7 days and we could really do with native speakers checking the translations before we put it live.

**Comment by readingdancer** [comment]
I will close this issue now, as the list has been updated :)
