### ISSUE TITLE
Update summary banner at the top of page & link summaries to user-selected need

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#26]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

The banner at the top of the page is composed of four panels that summarize various aspects of the resources within the database.

Currently, the text of the banners and the icons used are fixed. 

(b) What do we need to code next?
 We want the banner to change as the user selects different options from the "What do you need?" drop-down menu. The t items in the list below indicate how the content of the 4 panels should change as the user selects different options from the drop-down menu.

**Groceries**
         order & pay online
         curbside pick-up
         senior shopping hours
         discounts for medical workers

**Restaurants**
            order & pay online
            curbside pick-up
            delivery
            discounts for medical workers

**Family Meal Kits**
            order & pay online
            curbside pick-up
            delivery
            discounts for medical workers

**Free Meals** 
            meals open to the public
            meals for students
            free grocery locations
            free produce locations

**Pharmacy**
            order & pay online
            curbside pick-up
            delivery
            senior shopping hours

**Pet Supplies**
            order & pay online
            curbside pick-up
            delivery
            discounts for medical workers

**Entertainment**
              movie theaters
              virtual lessons
              virtual workouts
              curbside pick-up 

**Describe alternatives you've considered**
N/A

**Additional context**
The banner summaries pull from the database. In order to support new banner summaries (e.g., "order & pay online"), that information needs to be coded into the database. Coordinate with our data manager (Allison Kittinger) on the necessary changes.

![Screen Shot 2020-03-28 at 12 07 57 AM](https://user-images.githubusercontent.com/58799043/77814531-38db9800-7088-11ea-85b0-c26c4467f164.png)

**Comment by readingdancer** [comment]
I have just released a new version of the code where the majority of the above is now working with the appropriate translatable text and calculating all the correct figures from our data.

I have added some additional columns to the spreadsheet and populated them where possible from the data we already had in the information column. There are also additional columns for the extra data required to make the above counters work :)

https://github.com/code-for-chapel-hill/COVID-Support-For-CH/releases/tag/v0.0.10-alpha

**Comment by readingdancer** [comment]
This has been completed other than the entertainment section, @KM-Hanson if we get anything in that category I suggest we raise a new ticket to add it.
