### ISSUE TITLE
Add "About" section with project information

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#27]
**Have an idea for an additional feature?**
(a) Describe the feature

We need an "About" section. Decisions to make: (1) where to place the "about" marker, (2) what text to use for the marker ("About Us"?) and (3) how the feature will function (will it be a pop-up box? navigate to a separate page?)

The information included in the section could be as follows:

This page is powered by the Chapel Hill Brigade of Code for America. Our database of resources is created with the help of our partners:

Chapel Hill/Orange County Visitors Bureau
Downtown Chapel Hill Partnership
#LocalListNC

(b) How does it need to perform?

(c) How will we code it?

**Describe alternatives you've considered**

**Additional context**

**Comment by KM-Hanson** [comment]
@suddengenesis You are working on this, yes?

**Comment by suddengenesis** [comment]
Here's one rough idea of how this might work. What do you think? 
<img width="1031" alt="Screen Shot 2020-03-29 at 1 40 53 AM" src="https://user-images.githubusercontent.com/24510849/77842290-96421880-715e-11ea-9fa6-10a96abd8d4f.png">
We can pick from quite a few other icons for the button, too: https://bootstrap-vue.js.org/docs/icons

**Comment by suddengenesis** [comment]
It looks like it will work pretty well for mobile phones, too. I also turned the organization names into links and have all the text pulled out to be translated.
<img width="340" alt="Screen Shot 2020-03-29 at 2 30 16 AM" src="https://user-images.githubusercontent.com/24510849/77842869-5af71800-7165-11ea-9020-1ddbc9cffcbf.png">

**Comment by readingdancer** [comment]
I think it looks good for now, it will all depend how much content @KM-Hanson would like to put in this area. I can imagine that this might need to end up being a full page of it own in the future.

I think we will want to have links to the GitHub page for people who might want to help contribute, we can then easily put a lot more information on the github pages about contributing data as well as code.

**Comment by KM-Hanson** [comment]
@suddengenesis  I think this looks great! I like the solution to just use an icon on the page to save on space and make it a workable solution for mobile.

3 quick fixes:

 (1) I have the name of one of the partners wrong - it should be "Chapel Hill Downtown Partnership"

(2) We should add Carolina Farm Stewardship Association
https://www.carolinafarmstewards.org/on-farm-pickups/

(3) I think the last sentence should read "Our database of resources benefits from information collected by these organizations:". I'd like to add the farm stewardship as a resource but I don't know them well enough yet to say that we are partners. This way, we can list that source even if I don't have a chance to connect with them before the page goes up.

Thanks!

**Comment by suddengenesis** [comment]
@KM-Hanson @readingdancer I've spruced this up a bit - what do you think?
<img width="520" alt="Screen Shot 2020-03-29 at 1 06 22 PM" src="https://user-images.githubusercontent.com/24510849/77855397-2fece280-71be-11ea-9be6-4b41b5f62296.png">
<img width="520" alt="Screen Shot 2020-03-29 at 1 06 31 PM" src="https://user-images.githubusercontent.com/24510849/77855398-30857900-71be-11ea-9556-f64beb1d69fd.png">
<img width="520" alt="Screen Shot 2020-03-29 at 1 06 40 PM" src="https://user-images.githubusercontent.com/24510849/77855399-30857900-71be-11ea-9a64-a61a1775c836.png">

**Comment by KM-Hanson** [comment]
@suddengenesis 
I like it! What is the Slack link? Is that the invitation link that I sent you? Let's wait to include that until we get input from @garrisonreid 

I would add some text encouraging other communities to replicate the project.

**Suggested new text for the Get Involved tab:**

"This is an open-source project <add link to license info when ready>. **You** can build a database for your community and join our site or make your own in just 3 steps! No engineering skills needed.
 
(1) Reach out to local government and business associations to gather information.
(2) Organize resource information using our spreadsheet template <add link when we create template doc>.
(3) Email us <add link> when you are ready to join the NC site.
-or-
 Duplicate a site for your state.

Developers - find our [source code](https://github.com/code-for-chapel-hill/COVID-Support-For-CH) and [Code of Conduct](https://github.com/codeforamerica/codeofconduct) on GitHub."

**Comment by KM-Hanson** [comment]
@suddengenesis this part got lost in my comment.....

we should link to our license info & spreadsheet template.... but we don't have those ready yet :) i'll create issues for those items.

**Comment by suddengenesis** [comment]
Sounds good! I think this is close enough that I'm going to recommend merging it back into `master` to avoid conflicts. There are a few minor things I'd like to fix, but we can open separate lower priority issues for these:

1. When the screen is short enough, the top of the modal is clipped by the navigation bar. This loses about a third of the 'X' to close, but the title is still fully legible.
2. I would prefer to have all the organization links come from a JSON data source file but didn't want to hold this up on investigating how to do that with Vue and Bootstrap.
3. Likewise, the "Chapel Hill Brigade" and "Code for America" orgs could come from a data file, but I'm a little less concerned about that.

**Comment by readingdancer** [comment]
Hi Adam,
On your point about the data file, I was actually thinking that if we find we continue to build this site, we might want to have a real "back office" content management system and as such, this would all be part of the "content".
I wouldn't worry about separating them out for now, like you said we have enough other priority tickets on our plate :)
Cheers, Chris
