### ISSUE TITLE
Add a way for "Add your business" to the site

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#28]
**Have an idea for an additional feature?**
(a) Describe the feature

It would be nice to have a way for business owners to suggest that their business be added to our database. Should this option live on the "About Us" page? Or should it be a button at the top of the screen?

(b) How does it need to perform?

We don't want the information to automatically be added to the database. I think we want to be able to review submissions before adding them. We want to make sure that any food providers are licensed commercial kitchens and not folks starting a bakery, etc. out of their home.

(c) How will we code it?

**Describe alternatives you've considered**

**Additional context**

**Comment by KM-Hanson** [comment]
@readingdancer Can we mark this closed?

**Comment by readingdancer** [comment]
Yes :)
