### ISSUE TITLE
Add padding around the map so that scroll bar still works on mobile devices

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#29]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

We need whitespace/padding around the map so that the page scrollbar is still visible/functional on mobile devices. Otherwise, the user gets trapped with the map filling the bottom half of the screen and no way to scroll back up to the top of the page.

(b) What do we need to code next?

**Describe alternatives you've considered**
 
The solution might not be padding or whitespace - we just need a fix so that users don't get trapped on the map feature when viewing the page on a mobile phone.

**Additional context**

**Comment by readingdancer** [comment]
I have fixed this issue, it should no longer be a problem. We actually don't need to add bars at the side, there was another issue with the site that was causing the problem, so I will close this ticket.
