### ISSUE TITLE
Limit geographic zoom of the map

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#30]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

Can we limit the geographic zoom of the map so that users can't accidentally "zoom out" to the entire US, etc.? Can we limit the max zoom to be slightly larger than NC?

(b) What do we need to code next?

https://leafletjs.com/examples/zoom-levels/

**Describe alternatives you've considered**

**Additional context**

**Comment by readingdancer** [comment]
Thanks Adam, all fixed :)
