### ISSUE TITLE
Markers on map disappear when navigating back from a linked resource

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#31]
**Describe the bug**
In the current version, when the user clicks on a marker on the map, they see a pop-up call-out that gives the resource name, address, and phone number. The resource name is linked to the establishment's website when available. 

When you click on a link to navigate to an external webpage, and then click the "back" button on your browser, you return to our site but the map is blank. None of the markers show up. You have to select a different option from the "What do you need?" drop-down to get the markers to show up again.
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by suddengenesis** [comment]
I just tried to reproduce this in both Chrome and Safari on a Mac laptop, as well as Edge and Chrome on a Windows 10 machine but didn't see it happen. The markers all showed when I clicked "back." Is there a particular OS/browser where this still occurs?

**Comment by KM-Hanson** [comment]
OK - I tried to reproduce the error myself and I could not. I'll do a better job of documenting the behavior if I see it again :)

**Comment by readingdancer** [comment]
@KM-Hanson Is this still an issue? If not, can you move it from the Ice Box to Done?

**Comment by KM-Hanson** [comment]
Moved to "Done". This was an early issue and I could not re-create it. Issue closed.
