### ISSUE TITLE
Link page to Google Analytics?

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#33]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

We should devise a way to view information on how many people use the site and how they are interacting with the site.

(b) What do we need to code next?

Is Google Analytics the best solution for this?

**Describe alternatives you've considered**

**Additional context**

**Comment by readingdancer** [comment]
@suddengenesis Is helping to work on the COVID-19 site, @garrisonreid do you know if we have a group account for Google Analytics? If so, could you have a chat with Adam on Slack?

**Comment by suddengenesis** [comment]
In looking into this, we realized we may be able to get access to G Suite as part of Code for America so we can set up a group rather than individual user for some of this access. There may be some other implications for this, though, like transferring http://www.codeforchapelhill.com/ to their registrar. Discussion continues on Slack.

**Comment by suddengenesis** [comment]
Important to note that according to https://marketingplatform.google.com/about/analytics/terms/us/:

> You will have and abide by an appropriate Privacy Policy and will comply with all applicable laws, policies, and regulations relating to the collection of information from Users. You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies, identifiers for mobile devices (e.g., Android Advertising Identifier or Advertising Identifier for iOS) or similar technology used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data.

We should definitely figure out where this would live and what it would contain before working on setting up Analytics.

**Comment by readingdancer** [comment]
I have added Google Analytics and setup a new ticket for the privacy policy:

https://github.com/code-for-chapel-hill/COVID-Support-For-CH/issues/87
