### ISSUE TITLE
Develop "list view" for resources

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#34]
**Have an idea for an additional feature?**
(a) Describe the feature

We need a way to provide a "list view" of the resources. This could be expanded information for one resource or could be a list of all of the resources that match the filter criteria. See screenshots below for 3 different options from a Google map search.

![Screen Shot 2020-03-28 at 1 18 39 AM](https://user-images.githubusercontent.com/58799043/77815507-18184000-7092-11ea-8c98-4360faab4880.png)

![Screen Shot 2020-03-28 at 1 18 20 AM](https://user-images.githubusercontent.com/58799043/77815509-18b0d680-7092-11ea-8ecd-ddb7b28d7aee.png)

![Screen Shot 2020-03-28 at 1 17 53 AM](https://user-images.githubusercontent.com/58799043/77815510-19496d00-7092-11ea-9baa-48759cd06544.png)

(b) How does it need to perform?

(c) How will we code it?

**Describe alternatives you've considered**

**Additional context**

**Comment by readingdancer** [comment]
The list view is built and working well.
