### ISSUE TITLE
Finalize the Leaflet tile choice

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#35]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

We need a tile theme that is not too busy visually but also not so bland that it makes it hard to recognize what part of town you are looking at. The current version seems a bit busy (for example, the trails included in the North Forest area are distracting).

(b) What do we need to code next?

**Describe alternatives you've considered**

List of basemaps available from Carto:
https://carto.com/help/building-maps/basemap-list/
https://carto.com/developers/carto-vl/reference/#cartobasemaps

These are two nice options:

![Screen Shot 2020-03-28 at 1 36 33 AM](https://user-images.githubusercontent.com/58799043/77815871-b2798300-7094-11ea-99a0-599e02844956.png)

![Screen Shot 2020-03-28 at 1 36 25 AM](https://user-images.githubusercontent.com/58799043/77815872-b2798300-7094-11ea-8fb6-33d334a64ea6.png)

**Additional context**

**Comment by readingdancer** [comment]
We changed the tiles and everyone is happy with them now :)
