### ISSUE TITLE
Fix wording on "free produce" pane within Free Meals banner

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#42]
**Describe the bug**
Last panel reads "Free produce location" - should read "Free produce locations" to match "Free grocery locations"

![Screen Shot 2020-03-28 at 11 31 07 PM](https://user-images.githubusercontent.com/58799043/77839620-67bb4200-714c-11ea-8038-b99e9f40f128.png)

**Comment by suddengenesis** [comment]
I think this one should be fixed alongside #43 to get the plural working correctly.

**Comment by KM-Hanson** [comment]
@suddengenesis Yes - I agree. Listed this one separately as a minimum fix. At minimum, the wording in these two boxes should match, even if we don't fix #43.
