### ISSUE TITLE
Add "Farms & Farmers Markets" to drop-down menu

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#45]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

There are actually a lot of farm stands and farmers markets that are still operational and have pick-up and/or delivery options. 

To encourage people to support local farmers we should (a) have this as a drop-down feature and (b) also list these businesses as "grocery" so they show up if someone is searching for groceries.

(b) What do we need to code next?

Add a drop-down "Farms & Farmers Markets"

**Comment by readingdancer** [comment]
I think we can close this one @KM-Hanson as I think we agreed to keep it as it has now been implemented?

**Comment by KM-Hanson** [comment]
Yes - we can close #45.

'Farms & Farmers' Markets' now appears as an item in the drop-down menu. We will not cross-post Farmers' Markets in the 'Groceries' category.
