### ISSUE TITLE
Add summary banner for "Farms & Farmers Markets" resource option

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#46]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

The "Farms & Farmers Markets" resources should have the following panels in the summary bar at the top of the page:

Curbside pick-up
On-farm pick-up
Farmers markets
Online order & pay

**Comment by KM-Hanson** [comment]
@amkitt We will need 2 additional columns in the dataset to support the summary panels here (1) on_farm (0/1) and farmers_market (0/1)

**Comment by readingdancer** [comment]
Hi @KM-Hanson 

I have added the new Farm section and have added one test entry to the Spreadsheet which you are welcome to delete when real data is added.

We will still need to add the additional data files so some of the numbers at the top are not yet real. I will wait until you have merged all of your changes into the live table before trying to plumb that in.

Cheers, Chris

**Comment by readingdancer** [comment]
This has all been finished so I am closing this ticket.
