### ISSUE TITLE
Add drop-down for "Prepared Family Meals" resources

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#47]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

Many restaurants are re-tooling to offer prepared meals once or twice a week instead of regular service. We should have a separate drop-down option to highlight these resources.

(b) What do we need to code next?

Add "Prepared Family Meals" to the drop-down list.

**Comment by KM-Hanson** [comment]
@readingdancer This seems to be complete. One small edit - add a hyphen to pre-order:


![Screen Shot 2020-04-01 at 12 41 58 AM](https://user-images.githubusercontent.com/58799043/78100057-c2090c80-73b1-11ea-9a3f-e291478d4a51.png)

**Comment by readingdancer** [comment]
Added the text, it will be in the next release :)
