### ISSUE TITLE
Decide how to cross-post farms as "Groceries"

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#49]
**Need work on an existing feature? **

In order to drive customers to support local farms and farmers markets, we should cross-list all of our "farm" resources as "groceries" so that they show up when someone asks to see grocery resources.

How should we achieve this? 

Add another column for the secondary listing?

OR

Copy & paste all of the "farm" resources and list them as "grocery" as well?

**Comment by readingdancer** [comment]
@KM-Hanson  Definitely not the Copy & Paste option :)

To me, it sounds like these should potential all be listed under Grocery and we should have two additional flags to say these are Farm or Farm Market.

If this data set increases a lot, we can always split them into their own section?

**Comment by readingdancer** [comment]
This ticket is related to issue #46

**Comment by KM-Hanson** [comment]
There could be 15-20 entries that are farms or farmers markets, based on what I am finding for Orange County. I think it would be good to list Farms & Farmers Markets as a separate section.  I like having a separate drop-down item for the farms because as a user/consumer it triggers me to think "oh yeah - we have lots of farms in our area! we are so fortunate. I should do what I can to support those farms." It would not have crossed my mind otherwise, and these locations are farther out of town so not really the first choice most users would make based on geographic proximity. I'm afraid they would get ignored if they were just folded into the
"Groceries" drop-down item. @readingdancer What do you think?

**Comment by readingdancer** [comment]
Yes indeed, if there are that many it sounds like a good idea. However I think your point of them being lost might also be a reason to not include them on the Groceries section. IMHO it's confusing to show them on both.

However, we do have another option which we have not discussed yet, which is to show different pin points. E.g. One could have a tractor in the head of the pin point and the other a basket? ( also different colors to make them stand out as being different. )

What do you think :) ?

**Comment by KM-Hanson** [comment]
OK, good points. I vote for having a separate "Farms & Farmers Markets" section and then leaving those resources out of the "Groceries" section.

**Comment by readingdancer** [comment]
I think we can close this ticket :)
