### ISSUE TITLE
Need information on which edition of the web page is being shown (Orange County, etc.)

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#50]
****Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.**

We need a way to communicate the geographic extent of the resources shown on the map.

We should have this on our page, even if the project does not grow beyond Orange County. Folks are not going to pay attention to the URL to notice that our site is intended for Orange County.

Also, having the geography clearly communicated will be essential as we (potentially) scale up and let folks build databases for other cities and counties.

**(b) What do we need to code next?**

Adjust page title bar to read "COVID-19 Community Resources - Orange County, NC"?
Open to other suggestions.

**Comment by readingdancer** [comment]
I think we should leave the title as it is, it's short and precise and current fits on a mobile device. If we make the title any longer it's going to start wrapping.

My thought it we add a little "note" in the left hand, see the attached screen grab of an example.

![Orange County Idea](https://user-images.githubusercontent.com/4398217/78049323-ec72af80-7348-11ea-88f8-a0db26f7a21c.jpg)

**Comment by KM-Hanson** [comment]
I like the approach!

Small suggested edit:

”Currently, this site supports Orange County, NC. With your help, we can
expand our coverage.”


And maybe make the font one notch larger?

**Comment by readingdancer** [comment]
@KM-Hanson how about this?

![OC Info 2](https://user-images.githubusercontent.com/4398217/78052923-cc91ba80-734d-11ea-85b2-ecdd8e98ad78.jpg)

**Comment by KM-Hanson** [comment]
Great solution! Yes, now very noticeable.

**Comment by readingdancer** [comment]
We have agreed that the info panel I added covers this ticket for now, if our reach expands we will just need to raise a new ticket.
