### ISSUE TITLE
Create "Shop Safe" pop-up box

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#54]
****Have an idea for an additional feature?**
(a) Describe the feature**

I think we should have a positive peer-pressure reminder when visitors first land on the site.

**(b) How does it need to perform?**

Can we have a pop-up box (similar to the About box) that automatically is up when someone first visits the site? They user would have to click the X to dismiss.

Suggested text:

"Please, SHOP SAFE!
(1) If you are sick, stay home.
(2) Stay 6 ft. apart when shopping.
(3) Wash your hands often."

**Comment by KM-Hanson** [comment]
We chatted about having this as part of the side-bar on the left when a user first visits the page. A pop-up box that needs to be dismissed would make the site less accessible for visitors.

**Comment by readingdancer** [comment]
Just for the record, this is what I suggested we implement and it will be in my next deployment.
![hands](https://user-images.githubusercontent.com/4398217/78101584-f1217d00-73b5-11ea-8716-1f05d54fed41.jpg)

**Comment by readingdancer** [comment]
This is now live so we can close this ticket.
