### ISSUE TITLE
Align text on information box 

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#67]
**Need work on an existing feature? **

Can we move the text or resize the icon so that the word "coverage" is in-line with the rest of the text?

![Screen Shot 2020-04-01 at 12 33 37 AM](https://user-images.githubusercontent.com/58799043/78099796-047e1980-73b1-11ea-9364-10d1fc9cdfe0.png)

**Comment by readingdancer** [comment]
@KM-Hanson Which browser are you using and on what device?

I see the following on Chrome on a PC:

![info-snip](https://user-images.githubusercontent.com/4398217/78100338-802c9600-73b2-11ea-9f1e-9f158b54cdd3.jpg)

**Comment by KM-Hanson** [comment]
@readingdancer I'm on Chrome Version 80.0.3987.116 on a Mac.

**Comment by KM-Hanson** [comment]
This also happens on my mobile version.

**Comment by readingdancer** [comment]
This has been fixed, please confirm you are happy and close this ticket @KM-Hanson

**Comment by KM-Hanson** [comment]
Yes - looks good on Chrome on my Mac and also on the mobile version.
