### ISSUE TITLE
Have day of the week scroll bar start on Monday instead of Sunday?

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#68]
![Screen Shot 2020-04-01 at 12 48 58 AM](https://user-images.githubusercontent.com/58799043/78100438-c4b83180-73b2-11ea-82e3-681cbad492c9.png)
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

It seems more intuitive to have the scroll bar for day of the week start on Monday rather than on Sunday. Is that an easy edit?

**Comment by readingdancer** [comment]
This is done :)
