### ISSUE TITLE
Update text and links for the "About us" section

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#69]
Screenshots of the current content are below. These will need some text updating (possibly adding partners) and updates to some links (including the contact email).

![Screen Shot 2020-04-01 at 1 31 46 AM](https://user-images.githubusercontent.com/58799043/78102656-db618700-73b8-11ea-96a8-e7ef08d6dd26.png)

![Screen Shot 2020-04-01 at 1 31 39 AM](https://user-images.githubusercontent.com/58799043/78102663-e1effe80-73b8-11ea-9fa6-10328a94694a.png)

![Screen Shot 2020-04-01 at 1 31 30 AM](https://user-images.githubusercontent.com/58799043/78102680-e87e7600-73b8-11ea-9dd1-a5be8ab632f8.png)

**Comment by suddengenesis** [comment]
I’d fixed the `label.email_lowercase` to read `email`. It now has the real email there which looks even better. I also see the email link on the third bullet item of the `Get Involved` tab. What other changes are needed here?

**Comment by KM-Hanson** [comment]
@suddengenesis Yes, agreed that the full email looks better.

The "Get Involved" text should be improved. Here is a suggestion, open to your edits:

----------------------------------------------------------------------

This is an open-source project, built to share and expand to other communities.

**Add your community to our map for North Carolina:**
(1) Email us at contact@nccovidsupport.org.
(2) Reach out to local government and business associations to gather information.
(3) Use our spreadsheet and fillable forms to collect and organize local data.


**Use our code to build a site for your state:**
Developers - find our source code, Code of Conduct and license on GitHub.

**Comment by KM-Hanson** [comment]
@readingdancer Added a "help us build our database" section to my prior suggestion - what do you think?

--------------------

This is an open-source project, built to share and expand to other communities.

**Help us build our database:**
- Add a new business or resource.
- Update an existing entry.

**Become a partner community on our map for North Carolina**:
(1) Email us at contact@nccovidsupport.org.
(2) Reach out to local government and business associations to gather information.
(3) Use our spreadsheet and fillable forms to collect and organize local data.

**Use our code to build a site for your state or region:**
Developers - find our source code, Code of Conduct and license on GitHub.

**Comment by readingdancer** [comment]
How about this?
----
This is an open-source project, built to share and expand to other communities.

**Help us to help your local community**
We have created the following two Google forms to help you [add a new business or resource](url) and a second form to [updating an existing entry](url).

**Would you like to become a local community ambassador?**
We are looking for people who currently have some spare time and would like to help gather up to date information about the businesses and resources in their local area.

To be an ambassador you would need to:

1. Reach out to local government and business associations to gather information.
2. Use our spreadsheet and fill able forms to collect and organize local data.

If this interests you, please email us at contact@nccovidsupport.org and we will get right back to you with all the details.

**Use our code to build a site for your state or region:**
Developers - find our source code, Code of Conduct and license on GitHub.

**Comment by KM-Hanson** [comment]
@readingdancer   Good points! A few more tweaks to bring down the text volume:

-----------------------------
This is an open-source project, built to share and expand to other communities.

**Support your neighbors and local businesses - help us grow!**
Use our online forms to add a business or update an existing entry.

**Become a community ambassador**
Help us expand coverage across North Carolina. Ambassadors will work with local government and business associations to bring NC COVID Support to their community. Email us at contact@nccovidsupport.org for tools and resources to get started.

**Use our code to build a site for your state or region:**
Developers - find our source code, Code of Conduct and license on GitHub.
