### ISSUE TITLE
Add auto-translations for additional languages

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#91]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

These are additional languages that are in need in Orange County. County officials will help us find translators to verify the text when we have the auto-translated draft prepared.

Mandarin Chinese
Japanese
Arabic
Karen/Burmese
Kinyarwanda 

(b) What do we need to code next?

Generate json files for the additional languages from the auto-translate app.

**Comment by readingdancer** [comment]
I have added:

Mandarin Chinese
Japanese
Arabic
Karen/Burmese

Will need to figure out Kinyarwanda tomorrow, also perhaps a future ticket we should add would be to make the site work Right to Left for the Arabic language!

**Comment by KM-Hanson** [comment]
@readingdancer Great - thanks!

Please go ahead and make the file for the Arabic translation, and I will include that in the translation request that we send to our partners. I have a software contact who can advise us on supporting right-to-left languages.

**Comment by readingdancer** [comment]
@KM-Hanson I have built two sites with RTL and I also did various pull requests in the past to extended the Umbraco CMS to support RTL languages, but always happy to have more help on this project :)
