### ISSUE TITLE
Small edit to the meta description

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#93]
**Describe the bug**
The current text might give the impression that the site lists many different types of free resources:

North Carolina community resources during the COVID-19 Coronavirus pandemic. Free meals, groceries, produce, pharmacies, pet supplies & senior citizen hours.

Suggested edit:

COVID-19 updated information for North Carolina communities. Find free meals & how to shop restaurants, groceries, pharmacies, and local businesses.

**Comment by readingdancer** [comment]
Hi @KM-Hanson 

The current live text includes more words that I think people might try to search, is there any way we can re-word to also include the Pets & Seniors?

How about we put the free meals at the end of the list?

**NC COVID Support - Community Resources for North Carolina**
Find groceries, produce, pharmacies, pet supplies, senior citizen hours & free meals in North Carolina during the COVID-19 Coronavirus pandemic.

The above shows another option with the title text above as both my original text and yours started with similar words to the title, so I have moved them to the end of the sentence.

What do you think?

**Comment by KM-Hanson** [comment]
@readingdancer How about a mix of the two? The primary feature of our site that makes us more helpful than anything else right now is the up-to-date information. So I think it would be good to stress that "COVID updated" point.


**NC COVID Support - Community Resources for North Carolina**
COVID-19 updated information on groceries, produce, pharmacies, pet supplies, senior citizen hours & free meals in your NC community.

**Comment by readingdancer** [comment]
In the end we went with:

"Find updated COVID-19 information on groceries, produce, pharmacies, pet supplies, senior citizen hours, free meals and more in North Carolina."
